# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = ["ata_piix" "mptspi" "uhci_hcd" "ehci_pci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-label/boot";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  networking.useDHCP = false;
  networking.interfaces.ens33.useDHCP = true;
  networking.networkmanager.enable = true;
  networking.hostName = "vm-dev";

  time.timeZone = "America/Chicago";

  # Enable the X11 windowing system.
  services.xserver.enable = true;

  # Enable the Plasma 5 Desktop Environment.
  services.xserver.displayManager.sddm.enable = true;
  services.xserver.desktopManager.plasma5.enable = true;
  services.xserver.xkbOptions = "ctrl:nocaps";

  virtualisation.vmware.guest.enable = true;
  boot.kernelPackages = pkgs.linuxPackages_5_15;
  hardware.video.hidpi.enable = true;

  # Don't require password for sudo
  security.sudo.wheelNeedsPassword = false;
  # Select internationalisation properties.
  i18n.defaultLocale = "en_US.UTF-8";
  environment.systemPackages = with pkgs; [
    xclip
    gtkmm3
  ];

  # Enable the OpenSSH daemon.
  services.openssh.enable = true;
  services.openssh.passwordAuthentication = true;
  services.openssh.permitRootLogin = "no";
  networking.firewall.enable = false;
  users.mutableUsers = false;
  users.users.ncwade.hashedPassword = "$6$FqyCyPBy4vTu8Gzs$z0nAfviYQ5dgxe2WdQ3zNIA8ulnKsBb5hhnnpulIrigqr.FLxgWftqMVVpumnU6FxwXwD/OJcK2YHumZjk2cO0";
}
